server:
  port: 9090

cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
      access-key: xxx
      secret-key: xxx
    sqs:
      endpoint: https://sqs.ap-south-1.amazonaws.com/992933636053/order-queue
